### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by somehowchris** [Gelbpunkt/hyper-trust-dns#1]
Hey :)

Lovely crate, like :rocket:

Do you plan on maintaining it? Just saw that `trust-dns-resolver` had some updates and rust 2021 was released.

Just let me know if I can help somehow or open PRs

**Comment by Gelbpunkt** [comment]
Hi there, of course I plan to maintain this crate 😄 
You're right, `trust-dns-resolver` 0.21 is out, and I'll update it in a commit and release later today.
I didn't want to move to rust 2021 yet because some crates that depend on this used to be on 2018, but that has changed since so I'll update this too.

**Comment by Gelbpunkt** [comment]
Done, version 0.4.0 with all that stuff and much more should be published now :tada:

**Comment by somehowchris** [comment]
No worries 🥂 

Do you use something like `dependabot` or `renovate`? They would open up a PR in GH which then automatically would run CI parts as new versions of dependencies are released. My experience with `renovate` so far has been great

**Comment by Gelbpunkt** [comment]
I haven't used them yet because I often find myself having to deal with breaking changes in dependency updates or wanting to change the API for a new major release myself. Simply bumping the dependency requirement won't do it in many cases, so I don't quite see a reason to use them asides from acting as release notifications.

**Comment by somehowchris** [comment]
Sure, well me speaking as just a human, I forget sometimes that this changed or updated. So I find it nice to at least have a notification in GitHub which I can tick off once I‘ve updated it

**Comment by Gelbpunkt** [comment]
Thanks for giving me a reason to do this, it was long overdue. I've added CI and dependabot.
